clusters_future = {
    "DV": {'col': '#d2eda2', 'display_name': 'DV', 'pango_lineages': [{'name': 'DV', 'url': None}]},
    "EA": {'col': '#f40afc', 'display_name': 'EA', 'pango_lineages': [{'name': 'EA', 'url': None}]},
    "EG.2": {'col': '#f953c9', 'display_name': 'EG.2', 'pango_lineages': [{'name': 'EG.2', 'url': None}]},
    "EG.4": {'col': '#94cb95', 'display_name': 'EG.4', 'pango_lineages': [{'name': 'EG.4', 'url': None}]},
    "EK": {'col': '#a7b2ec', 'display_name': 'EK', 'pango_lineages': [{'name': 'EK', 'url': None}]},
    "EL": {'col': '#61f30b', 'display_name': 'EL', 'pango_lineages': [{'name': 'EL', 'url': None}]},
    "EU": {'col': '#0a8c59', 'display_name': 'EU', 'pango_lineages': [{'name': 'EU', 'url': None}]},
    "FD": {'col': '#efc0e2', 'display_name': 'FD', 'pango_lineages': [{'name': 'FD', 'url': None}]},
    "FE": {'col': '#564fc4', 'display_name': 'FE', 'pango_lineages': [{'name': 'FE', 'url': None}]},
    "FG": {'col': '#938a6c', 'display_name': 'FG', 'pango_lineages': [{'name': 'FG', 'url': None}]},
    "FK": {'col': '#386301', 'display_name': 'FK', 'pango_lineages': [{'name': 'FK', 'url': None}]},
    "FY": {'col': '#f62f00', 'display_name': 'FY', 'pango_lineages': [{'name': 'FY', 'url': None}]},
    "FZ": {'col': '#d4737c', 'display_name': 'FZ', 'pango_lineages': [{'name': 'FZ', 'url': None}]},
    "GA": {'col': '#81cfc0', 'display_name': 'GA', 'pango_lineages': [{'name': 'GA', 'url': None}]},
    "GB": {'col': '#5952d7', 'display_name': 'GB', 'pango_lineages': [{'name': 'GB', 'url': None}]},
    "GD": {'col': '#fb9bfd', 'display_name': 'GD', 'pango_lineages': [{'name': 'GD', 'url': None}]},
    "XBF": {'col': '#94175b', 'display_name': 'XBF', 'pango_lineages': [{'name': 'XBF', 'url': None}]},
}